import { canonicalBytes, contentHash, parseCapabilities, revisionContentHash, sha256Hex, type PushChange, type SyncCapabilities, type SyncPage } from "../agentwiki/protocol";
import { mergeBody, mergeField, type StructuredConflict } from "../core/merge";
import type { LocalStatus, MoveHint, ScanResult } from "../core/model";
import { portablePathKey, validatePortablePath } from "../core/portable-path";
import { computeStatus, resolvePageIdentities, scanMapping } from "../core/status";
import type { ControlStorePort } from "../ports/control-store";
import type { PushRemotePort, SnapshotResult } from "../ports/push-remote";
import type { VaultPort } from "../ports/vault";
import { BaselineRepository, type BaselineState } from "../storage/baseline";
import { MutableControlRepository } from "../storage/envelope";
import { PullTransaction, type PullAction } from "./pull-transaction";
import { PushService } from "./push-service";
import type { SpaceMapping } from "./sync-coordinator";

export interface InitialBindingChoice { pageId:string; remotePath:string; remoteBody:string; localPath:string|null; localBody:string|null; localVaultByteHash:string|null; localCandidates:Array<{path:string;body:string;vaultByteHash:string}>; resolution:"local"|"remote"|"manual"|null; manualBody?:string }
export interface ConflictResolution { choice:"local"|"remote"|"manual"; manualValue?:string }
export interface PullPreview { scanEpoch: number; revision: string; actions: PullAction[]; remotePages: SyncPage[]; conflicts: StructuredConflict[]; conflictResolutions:Record<string,ConflictResolution>; initialBindings:InitialBindingChoice[] }
export interface PushPreview { revision: string; changes: PushChange[]; capabilities: SyncCapabilities }
interface RuntimeRemote extends PushRemotePort { snapshot(revision?: string): Promise<SnapshotResult>; getCapabilities?(): Promise<SyncCapabilities> }
interface PendingIdentities { schemaVersion: 1; entries: Record<string, { pageId: string; path: string; contentHash: string }> }
const isPendingIdentities=(value:unknown):value is PendingIdentities=>!!value&&typeof value==="object"&&(value as Partial<PendingIdentities>).schemaVersion===1&&typeof (value as Partial<PendingIdentities>).entries==="object";
interface MoveHintsState{schemaVersion:1;hints:MoveHint[]}
const isMoveHints=(value:unknown):value is MoveHintsState=>!!value&&typeof value==="object"&&(value as Partial<MoveHintsState>).schemaVersion===1&&Array.isArray((value as Partial<MoveHintsState>).hints);
const DEFAULT_CAPABILITIES: SyncCapabilities = { maxPageBytes:1048576,maxBatchBytes:4194304,maxBatchItems:100,maxChangeCount:5000,maxConfirmationBytes:4194304,maxClientSpacePages:5000,maxClientManifestBytes:4194304,maxClientTotalBodyBytes:104857600,maxResponseBytes:4194304,maxPageItems:200,pushSessionTtlSeconds:900 };
const safeKey=(value:string)=>value.replace(/[^A-Za-z0-9_-]/gu,"_");
const joinRoot=(root:string,relative:string)=>`${root}/${validatePortablePath(relative).path}`;

export class SyncRuntime {
  private scanEpoch=0;
  private readonly root:string;
  private readonly baseline:BaselineRepository;
  private readonly identities:MutableControlRepository<PendingIdentities>;
  private readonly moveHints:MutableControlRepository<MoveHintsState>;
  constructor(private readonly vault:VaultPort,private readonly control:ControlStorePort,private readonly remote:RuntimeRemote,private readonly mapping:SpaceMapping,private readonly fallbackCapabilities=DEFAULT_CAPABILITIES,deviceKey="local",spaceKey=safeKey(mapping.spaceId)){ this.root=`.agentwiki/devices/d-${safeKey(deviceKey)}/spaces/s-${safeKey(spaceKey)}`; this.baseline=new BaselineRepository(control,this.root,mapping.spaceId,mapping.rootPath); this.identities=new MutableControlRepository(control,`${this.root}/pending-identities.json`,isPendingIdentities);this.moveHints=new MutableControlRepository(control,`${this.root}/move-hints.json`,isMoveHints); }
  invalidate():void{this.scanEpoch+=1;}
  get spaceId():string{return this.mapping.spaceId;}
  async recordRename(fromPath:string,toPath:string):Promise<void>{const prefix=`${this.mapping.rootPath}/`;if(!fromPath.startsWith(prefix)||!toPath.startsWith(prefix))return;const base=await this.readBase();const page=Object.values(base.pages).find(item=>portablePathKey(item.relativePath)===portablePathKey(fromPath.slice(prefix.length)));const bytes=await this.vault.read(toPath);if(!page||!bytes)return;const current=await this.moveHints.read();const hints=(current?.payload.hints??[]).filter(item=>item.pageId!==page.pageId);hints.push({pageId:page.pageId,fromPath:page.relativePath,toPath:toPath.slice(prefix.length),observedVaultByteHash:await sha256Hex(bytes)});await this.moveHints.write({schemaVersion:1,hints});}
  private async readBase():Promise<BaselineState>{return this.baseline.read();}
  private async stageAndCommit(revision:string,pages:SyncPage[],kind:"pull"|"push"|"initialize"):Promise<void>{await this.baseline.prepare(revision,pages,kind);await this.baseline.commit();}
  private async capabilities():Promise<SyncCapabilities>{return parseCapabilities(this.remote.getCapabilities?await this.remote.getCapabilities():this.fallbackCapabilities);}
  private async snapshot(revision:string):Promise<SyncPage[]>{const value=await this.remote.snapshot(revision);const manifest={pages:value.items.map(page=>({pageId:page.pageId,path:page.path,title:page.title,contentHash:page.contentHash}))};const bodyBytes=value.items.reduce((total,page)=>total+new TextEncoder().encode(page.body).byteLength,0);const manifestBytes=value.items.length===0?0:canonicalBytes(manifest).byteLength;const hash=await revisionContentHash(manifest);if(value.revision!==revision||value.pageCount!==String(value.items.length)||value.revisionBodyBytes!==String(bodyBytes)||value.revisionManifestByteLength!==String(manifestBytes)||value.revisionContentHash!==hash)throw new Error("Snapshot integrity mismatch");return value.items;}
  private async scan():Promise<ScanResult>{const epoch=this.scanEpoch;const status=await this.vault.rootStatus(this.mapping.rootPath);if(status==="file")throw new Error("Mapping root is a file");if(status==="missing"&&this.mapping.status==="active")throw new Error("local scan incomplete: mapping root is missing");const capabilities=await this.capabilities();try{const result=await scanMapping(status==="missing"?[]:await this.vault.listMarkdown(this.mapping.rootPath),{complete:true,scanEpoch:epoch,capabilities:{pages:capabilities.maxClientSpacePages,bodyBytes:capabilities.maxClientTotalBodyBytes,manifestBytes:capabilities.maxClientManifestBytes}});if(epoch!==this.scanEpoch)throw new Error("scan epoch changed");return result;}catch(error){throw new Error(`local scan incomplete: ${error instanceof Error?error.message:"read failure"}`);}}
  async establishEmptyBase():Promise<void>{const head=await this.remote.getHead(this.mapping.spaceId);await this.stageAndCommit(head.revision,[],"initialize");}
  async recover():Promise<void>{const pullTx=new PullTransaction(this.vault,this.control,`${this.root}/pull`);const pull=await pullTx.inspect();let committedTransactionId:string|null=pull?.state==="committed"?pull.transactionId:null;if(pull&&!committedTransactionId)await pullTx.recover();await this.baseline.recover(committedTransactionId);const pushService=new PushService(this.remote,this.control,`${this.root}/push`);const push=await pushService.inspect();if(push&&push.localCommitPhase!=="verified"){const result=push.remoteState==="published"&&push.result?push.result:await pushService.resume();if(!result)throw new Error("PUSH_RECOVERY_REQUIRED");const base=await this.readBase();if(base.revision!==result.revision)await this.stageAndCommit(result.revision,await this.snapshot(result.revision),"push");await pushService.markVerified();}}
  async status():Promise<{baseRevision:string;remoteRevision:string;local:LocalStatus}>{const base=await this.readBase();const scan=await this.scan();const resolved=resolvePageIdentities(base.pages,scan.files,[]);const head=await this.remote.getHead(this.mapping.spaceId);return{baseRevision:base.revision,remoteRevision:head.revision,local:computeStatus(base.pages,resolved,scan)};}
  async previewPull():Promise<PullPreview>{
    const base=await this.readBase();const head=await this.remote.getHead(this.mapping.spaceId);const remote=await this.snapshot(head.revision);const scan=await this.scan();const localByPath=new Map(scan.files.map(file=>[portablePathKey(file.relativePath),file]));const actions:PullAction[]=[];const conflicts:StructuredConflict[]=[];const initialBindings:InitialBindingChoice[]=[];const finalKeys=new Set<string>();
    for(const page of remote){const remotePath=validatePortablePath(page.path).path;if(finalKeys.has(portablePathKey(remotePath)))throw new Error("PATH_COLLISION");finalKeys.add(portablePathKey(remotePath));const basePage=base.pages[page.pageId];const local=localByPath.get(portablePathKey(basePage?.relativePath??remotePath))??localByPath.get(portablePathKey(remotePath));
      if(!basePage){initialBindings.push({pageId:page.pageId,remotePath,remoteBody:page.body,localPath:local?.relativePath??null,localBody:local?.normalizedBody??null,localVaultByteHash:local?.vaultByteHash??null,localCandidates:scan.files.map(file=>({path:file.relativePath,body:file.normalizedBody,vaultByteHash:file.vaultByteHash})),resolution:local?null:"remote"});continue;}
      if(!local){const remoteChanged=basePage.contentHash!==page.contentHash||portablePathKey(basePage.relativePath)!==portablePathKey(remotePath)||basePage.title!==page.title;if(remoteChanged)conflicts.push({conflictId:`delete:${page.pageId}`,pageId:page.pageId,field:"delete",base:basePage.body,local:"",remote:page.body,wholeDocument:true});continue;}
      const pathMerge=mergeField(basePage.relativePath,local.relativePath,remotePath);const titleMerge=mergeField(basePage.title,local.title,page.title);const bodyMerge=await mergeBody(basePage.body,local.normalizedBody,page.body,page.pageId);conflicts.push(...bodyMerge.conflicts);if(pathMerge.conflict)conflicts.push({conflictId:`path:${page.pageId}`,pageId:page.pageId,field:"path",base:basePage.relativePath,local:local.relativePath,remote:remotePath,wholeDocument:true});if(titleMerge.conflict)conflicts.push({conflictId:`title:${page.pageId}`,pageId:page.pageId,field:"title",base:basePage.title,local:local.title,remote:page.title,wholeDocument:true});
      if(!pathMerge.conflict&&portablePathKey(pathMerge.value)!==portablePathKey(local.relativePath))actions.push({kind:"rename",fromPath:joinRoot(this.mapping.rootPath,local.relativePath),path:joinRoot(this.mapping.rootPath,pathMerge.value),body:bodyMerge.body});else if(bodyMerge.body!==local.normalizedBody)actions.push({kind:"write",path:joinRoot(this.mapping.rootPath,local.relativePath),body:bodyMerge.body});
    }
    const remoteIds=new Set(remote.map(page=>page.pageId));for(const page of Object.values(base.pages))if(!remoteIds.has(page.pageId)){const local=localByPath.get(portablePathKey(page.relativePath));if(local&&local.contentHash!==page.contentHash)conflicts.push({conflictId:`archive:${page.pageId}`,pageId:page.pageId,field:"archive",base:page.body,local:local.normalizedBody,remote:"",wholeDocument:true});else if(local)actions.push({kind:"trash",path:joinRoot(this.mapping.rootPath,page.relativePath)});}
    return{scanEpoch:scan.scanEpoch,revision:head.revision,actions,remotePages:remote,conflicts,conflictResolutions:{},initialBindings};
  }
  async bindInitialLocal(preview:PullPreview,pageId:string,localPath:string):Promise<void>{const scan=await this.scan();if(scan.scanEpoch!==preview.scanEpoch)throw new Error("scan epoch changed");const local=scan.files.find(file=>portablePathKey(file.relativePath)===portablePathKey(localPath));const binding=preview.initialBindings.find(item=>item.pageId===pageId);if(!local||!binding)throw new Error("Initial binding candidate is missing");if(preview.initialBindings.some(item=>item!==binding&&item.localPath!==null&&portablePathKey(item.localPath)===portablePathKey(localPath)))throw new Error("Local page is already bound");binding.localPath=local.relativePath;binding.localBody=local.normalizedBody;binding.localVaultByteHash=local.vaultByteHash;binding.resolution=null;}
  async applyPull(preview:PullPreview):Promise<void>{
    if(preview.conflicts.some(item=>!preview.conflictResolutions[item.conflictId])||preview.initialBindings.some(item=>item.resolution===null))throw new Error("Pull has unresolved structured conflicts");
    const boundKeys=new Set<string>();for(const item of preview.initialBindings)if(item.localPath){const key=portablePathKey(item.localPath);if(boundKeys.has(key))throw new Error("Local page is bound more than once");boundKeys.add(key);}
    const actions=[...preview.actions];const hints:MoveHint[]=[];
    for(const choice of preview.initialBindings){const body=choice.resolution==="manual"?choice.manualBody??choice.localBody??choice.remoteBody:choice.resolution==="local"?choice.localBody??choice.remoteBody:choice.remoteBody;if(choice.localPath){if(body!==choice.localBody)actions.push({kind:"write",path:joinRoot(this.mapping.rootPath,choice.localPath),body});if(choice.localVaultByteHash)hints.push({pageId:choice.pageId,fromPath:choice.remotePath,toPath:choice.localPath,observedVaultByteHash:choice.localVaultByteHash});}else actions.push({kind:"create",path:joinRoot(this.mapping.rootPath,choice.remotePath),body});}
    const base=await this.readBase();const scan=await this.scan();const moveHints=(await this.moveHints.read())?.payload.hints??[];const resolved=resolvePageIdentities(base.pages,scan.files,moveHints);
    for(const conflict of preview.conflicts){const resolution=preview.conflictResolutions[conflict.conflictId]!;const value=resolution.choice==="manual"?resolution.manualValue??conflict.local:resolution.choice==="remote"?conflict.remote:conflict.local;const local=resolved.find(file=>file.pageId===conflict.pageId);if(conflict.field==="body"&&local&&value!==local.normalizedBody)actions.push({kind:"write",path:joinRoot(this.mapping.rootPath,local.relativePath),body:value});else if(conflict.field==="path"&&local&&portablePathKey(value)!==portablePathKey(local.relativePath))actions.push({kind:"rename",fromPath:joinRoot(this.mapping.rootPath,local.relativePath),path:joinRoot(this.mapping.rootPath,validatePortablePath(value).path),body:local.normalizedBody});else if(conflict.field==="delete"&&resolution.choice!=="local"){const remote=preview.remotePages.find(page=>page.pageId===conflict.pageId);if(remote)actions.push({kind:"create",path:joinRoot(this.mapping.rootPath,remote.path),body:value});}else if(conflict.field==="archive"&&resolution.choice!=="local"&&local)actions.push({kind:"trash",path:joinRoot(this.mapping.rootPath,local.relativePath)});}
    const baselineTx=await this.baseline.prepare(preview.revision,preview.remotePages,"pull");await this.baseline.setPhase("applying");const tx=new PullTransaction(this.vault,this.control,`${this.root}/pull`);await tx.prepare(actions,preview.scanEpoch,baselineTx.transactionId);await tx.apply(this.scanEpoch);if(hints.length)await this.moveHints.write({schemaVersion:1,hints});await this.baseline.commit();this.mapping.status="active";
  }
  async previewPush():Promise<PushPreview>{const capabilities=await this.capabilities();const base=await this.readBase();const head=await this.remote.getHead(this.mapping.spaceId);const baseRevision=this.mapping.status==="pending"&&Object.keys(base.pages).length===0?head.revision:base.revision;if(head.revision!==baseRevision)throw new Error("BASE_STALE");const scan=await this.scan();const hints=(await this.moveHints.read())?.payload.hints??[];const resolved=resolvePageIdentities(base.pages,scan.files,hints);const local=computeStatus(base.pages,resolved,scan);if(local.ambiguous.length||(local.added.length>0&&local.deleted.length>0))throw new Error("IDENTITY_REQUIRED");const envelope=await this.identities.read();const identities:PendingIdentities=envelope?.payload??{schemaVersion:1,entries:{}};const changes:PushChange[]=[];const changed=new Map<string,(typeof local.added)[number]>();for(const file of [...local.added,...local.modified,...local.renamed])changed.set(file.pageId??`path:${portablePathKey(file.relativePath)}`,file);for(const file of changed.values()){let identity=Object.values(identities.entries).find(item=>item.path===file.relativePath)||Object.values(identities.entries).find(item=>item.contentHash===file.contentHash);const pageId=file.pageId??identity?.pageId??crypto.randomUUID();if(!file.pageId){identity={pageId,path:file.relativePath,contentHash:file.contentHash};identities.entries[pageId]=identity;}changes.push({operation:"upsert",pageId,path:file.relativePath,title:file.title,body:file.normalizedBody,contentHash:await contentHash(file.normalizedBody)});}await this.identities.write(identities);for(const page of local.deleted)changes.push({operation:"archive",pageId:page.pageId,previousPath:page.relativePath});return{revision:baseRevision,changes,capabilities};}
  async applyPush(preview:PushPreview):Promise<void>{if(!preview.changes.length)return;const service=new PushService(this.remote,this.control,`${this.root}/push`);const result=await service.publish({spaceId:this.mapping.spaceId,baseRevision:preview.revision,changes:preview.changes,capabilities:preview.capabilities});const pages=await this.snapshot(result.revision);await this.stageAndCommit(result.revision,pages,"push");await service.markVerified();this.mapping.status="active";}
}
